### ISSUE TITLE
Get Problems when use Code!

### ISSUE THREAD

**Issue by Tian14267** [modricwang/Pytorch-Model-to-TensorRT#10]
Hello,guys!  I get problems when I run main.py:
```
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    import calib as calibrator
  File "/home/fffan/fffan_files/Experiment/Pytorch-Model-to-TensorRT-master/calib.py", line 13, in <module>
    class PythonEntropyCalibrator(trt.infer.EntropyCalibrator):
AttributeError: 'module' object has no attribute 'infer'
```
My tensorrt is 5.1   Does someone know new API in 5.1?

**Comment by Tian14267** [comment]
@modricwang
