### ISSUE TITLE
Cannot install calib

### ISSUE THREAD

**Issue by nithinsubbiah** [modricwang/Pytorch-Model-to-TensorRT#5]
Tried to install the package using pip, but encountered an error due to python version mismatch. Pip package was last updated in 2015. How do I install this package?

**Comment by modricwang** [comment]
Hi, 
`calib` is not a package.
 ```
import calib as calibrator
```
means import from `calib.py` in this project

**Comment by Tian14267** [comment]
I Get this error when "import calib":
```
Traceback (most recent call last):
  File "/home/fffan/fffan_files/Experiment/Pytorch-Model-to-TensorRT-master/main.py", line 16, in <module>
    import calib as calibrator
  File "/home/fffan/fffan_files/Experiment/Pytorch-Model-to-TensorRT-master/calib.py", line 13, in <module>
    class PythonEntropyCalibrator(trt.infer.EntropyCalibrator):
AttributeError: 'module' object has no attribute 'infer'
```
My tensorRT is 5.1
